protoc --go_out=plugins=grpc:./auth --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/auth auth/auth.proto
protoc --go_out=plugins=grpc:./conversation --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/conversation conversation/conversation.proto
protoc --go_out=plugins=grpc:./errinfo --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/errinfo errinfo/errinfo.proto
protoc --go_out=plugins=grpc:./friend --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/friend friend/friend.proto
protoc --go_out=plugins=grpc:./group --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/group group/group.proto
protoc --go_out=plugins=grpc:./msg --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/msg msg/msgv3.proto
protoc --go_out=plugins=grpc:./msggateway --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/msggateway msggateway/msggateway.proto
protoc --go_out=plugins=grpc:./push --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/push push/push.proto
protoc --go_out=plugins=grpc:./rtc --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/rtc rtc/rtc.proto
protoc --go_out=plugins=grpc:./sdkws --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/sdkws sdkws/sdkws.proto
protoc --go_out=plugins=grpc:./third --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/third third/third.proto
protoc --go_out=plugins=grpc:./user --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/user user/user.proto
protoc --go_out=plugins=grpc:./wrapperspb --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/wrapperspb wrapperspb/wrapperspb.proto
protoc --go_out=plugins=grpc:./statistics --go_opt=module=github.com/BioforestChain/dweb-browser-im-protocol/statistics statistics/statistics.proto